import '../models/transaction.dart';

final List<Transaction> dummyTransactions = [
  Transaction(
    id: 't1',
    amount: 150.00,
    isIncome: true,
    category: 'Salary',
    note: 'Part-time work',
    date: DateTime.now().subtract(const Duration(days: 1)),
  ),
  Transaction(
    id: 't2',
    amount: 40.75,
    isIncome: false,
    category: 'Food',
    note: 'Dinner with friends',
    date: DateTime.now().subtract(const Duration(days: 2)),
  ),
  Transaction(
    id: 't3',
    amount: 120.00,
    isIncome: false,
    category: 'Transport',
    note: 'Taxi fare',
    date: DateTime.now().subtract(const Duration(days: 3)),
  ),
  Transaction(
    id: 't4',
    amount: 200.00,
    isIncome: true,
    category: 'Salary',
    note: 'Freelance project',
    date: DateTime.now().subtract(const Duration(days: 4)),
  ),
  Transaction(
    id: 't5',
    amount: 60.00,
    isIncome: false,
    category: 'Bills',
    note: 'Electricity bill',
    date: DateTime.now().subtract(const Duration(days: 5)),
  ),
  Transaction(
    id: 't6',
    amount: 30.00,
    isIncome: false,
    category: 'Food',
    note: 'Lunch at cafe',
    date: DateTime.now().subtract(const Duration(days: 6)),
  ),
  Transaction(
    id: 't7',
    amount: 500.00,
    isIncome: true,
    category: 'Salary',
    note: 'Monthly salary',
    date: DateTime.now().subtract(const Duration(days: 7)),
  ),
  Transaction(
    id: 't8',
    amount: 15.00,
    isIncome: false,
    category: 'Transport',
    note: 'Bus ticket',
    date: DateTime.now().subtract(const Duration(days: 8)),
  ),
  Transaction(
    id: 't9',
    amount: 75.00,
    isIncome: false,
    category: 'Food',
    note: 'Grocery shopping',
    date: DateTime.now().subtract(const Duration(days: 9)),
  ),
  Transaction(
    id: 't10',
    amount: 300.00,
    isIncome: true,
    category: 'Salary',
    note: 'Bonus payment',
    date: DateTime.now().subtract(const Duration(days: 10)),
  ),
  Transaction(
    id: 't11',
    amount: 45.00,
    isIncome: false,
    category: 'Bills',
    note: 'Internet bill',
    date: DateTime.now().subtract(const Duration(days: 11)),
  ),
  Transaction(
    id: 't12',
    amount: 90.00,
    isIncome: false,
    category: 'Transport',
    note: 'Train ticket',
    date: DateTime.now().subtract(const Duration(days: 12)),
  ),
  Transaction(
    id: 't13',
    amount: 25.00,
    isIncome: false,
    category: 'Food',
    note: 'Coffee with a friend',
    date: DateTime.now().subtract(const Duration(days: 13)),
  ),
];
